// src/pkg/lockfile.rs
// SLIME.lock — deterministic dependency lockfile
// Written automatically by slimepkg. Never edit by hand.

use std::collections::HashMap;
use std::fs;
use std::path::Path;
use super::manifest::Version;

/// A fully resolved, locked dependency
#[derive(Debug, Clone)]
pub struct LockedPackage {
    pub name: String,
    pub version: Version,
    pub checksum: String,      // SHA-256 of the downloaded tarball
    pub registry: String,      // URL of registry that provided it
    pub dependencies: Vec<String>, // name@version strings of its own deps
}

#[derive(Debug, Clone)]
pub struct Lockfile {
    pub packages: HashMap<String, LockedPackage>, // key: "name@version"
}

impl Lockfile {
    pub fn new() -> Self {
        Lockfile {
            packages: HashMap::new(),
        }
    }

    pub fn key(name: &str, version: &Version) -> String {
        format!("{}@{}", name, version.to_string())
    }

    pub fn insert(&mut self, pkg: LockedPackage) {
        let k = Self::key(&pkg.name, &pkg.version);
        self.packages.insert(k, pkg);
    }

    /// Read SLIME.lock from disk
    pub fn from_file(path: &Path) -> Result<Self, String> {
        let content = fs::read_to_string(path)
            .map_err(|e| format!("Cannot read lockfile: {}", e))?;
        Self::parse(&content)
    }

    /// Parse SLIME.lock format
    pub fn parse(content: &str) -> Result<Self, String> {
        let mut lockfile = Lockfile::new();
        let mut current: Option<LockedPackage> = None;

        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                if line.is_empty() {
                    if let Some(pkg) = current.take() {
                        lockfile.insert(pkg);
                    }
                }
                continue;
            }

            if line.starts_with("[[package]]") {
                if let Some(pkg) = current.take() {
                    lockfile.insert(pkg);
                }
                current = Some(LockedPackage {
                    name: String::new(),
                    version: Version { major: 0, minor: 0, patch: 0 },
                    checksum: String::new(),
                    registry: String::from("https://registry.slime-lang.dev"),
                    dependencies: Vec::new(),
                });
                continue;
            }

            if let Some(ref mut pkg) = current {
                if let Some((key, val)) = line.split_once('=') {
                    let key = key.trim();
                    let val = val.trim().trim_matches('"');
                    match key {
                        "name"      => pkg.name = val.to_string(),
                        "version"   => pkg.version = Version::parse(val)?,
                        "checksum"  => pkg.checksum = val.to_string(),
                        "registry"  => pkg.registry = val.to_string(),
                        "dependencies" => {
                            pkg.dependencies = val
                                .trim_matches(|c| c == '[' || c == ']')
                                .split(',')
                                .map(|d| d.trim().trim_matches('"').to_string())
                                .filter(|d| !d.is_empty())
                                .collect();
                        }
                        _ => {}
                    }
                }
            }
        }

        if let Some(pkg) = current {
            lockfile.insert(pkg);
        }

        Ok(lockfile)
    }

    /// Serialize to SLIME.lock format
    pub fn to_string(&self) -> String {
        let mut out = String::new();
        out.push_str("# SLIME.lock — generated by slimepkg. Do not edit.\n\n");

        let mut keys: Vec<_> = self.packages.keys().collect();
        keys.sort();

        for key in keys {
            let pkg = &self.packages[key];
            out.push_str("[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", pkg.name));
            out.push_str(&format!("version = \"{}\"\n", pkg.version.to_string()));
            out.push_str(&format!("checksum = \"{}\"\n", pkg.checksum));
            out.push_str(&format!("registry = \"{}\"\n", pkg.registry));
            if !pkg.dependencies.is_empty() {
                let deps = pkg.dependencies
                    .iter()
                    .map(|d| format!("\"{}\"", d))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!("dependencies = [{}]\n", deps));
            }
            out.push('\n');
        }

        out
    }

    /// Write SLIME.lock to disk
    pub fn write(&self, path: &Path) -> Result<(), String> {
        fs::write(path, self.to_string())
            .map_err(|e| format!("Cannot write lockfile: {}", e))
    }

    pub fn is_locked(&self, name: &str, version: &Version) -> bool {
        self.packages.contains_key(&Self::key(name, version))
    }
}
